language: java
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6-dev-i386
  - sudo apt-get install lib32ncurses5-dev
  - sudo apt-get install libx11-dev
  - sudo apt-get install g++-multilib
  - sudo apt-get install lib32z1-dev
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar xf android-sdk_r22.6.2-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "y" | android update sdk --filter tools,platform-tools,build-tools-19.0.3,android-16 --no-ui --no-https -a
install:
  - gem install --version 0.8.9 faraday
  - gem install travis-artifacts
script: 
  - mvn clean install -DTRAVIS=true
env:
  global:
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=travis-nightly"
    - secure: "qi8EYqbwLzeNO9qsGlOtPStqucMxeMseubzmrafXtxzgp8fDGLacDcMlzKHj\n024vflz4w0j0LFU8QiphqTMvffzO9DlEbe9zo5NbUIYVeo4cXfGzPHzqHhVZ\n595N3pEDSSYmHo4/CFWoOOrcsExubWAxV3beKDGE4ggRcYzRzE4="
    - secure: "gMYt5SUHn0DR3dQNq9RHi8Y9VDij6Nnh+ZPsWcXePK0qpF3+IdRjID0hfoaw\ngq03xlIcRWUCTHHxHoPknhBn7JmRTjbpu26OVaQZJRpOEDlVWZhwWL8Idn7C\nt9q4EOW/ZWiVANTt65/j62dhaj16nvlii/gDDPIV3hU+X79Fquk="
